// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYYmyARnZ7PXj2osiu00ycsxecuqiMqj8',
    appId: '1:918558240173:web:caf0f0e60864d30778c524',
    messagingSenderId: '918558240173',
    projectId: 'music-videos-jjs',
    authDomain: 'music-videos-jjs.firebaseapp.com',
    databaseURL: 'https://music-videos-jjs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-videos-jjs.appspot.com',
    measurementId: 'G-6K4ZFNPYZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHEQiS38a1C4DwAT_qs50f_k2QXUbU0ZE',
    appId: '1:918558240173:android:587b6d8e618f618478c524',
    messagingSenderId: '918558240173',
    projectId: 'music-videos-jjs',
    databaseURL: 'https://music-videos-jjs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-videos-jjs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkh2JCnT6MV5KLeW_iYDmfeEitcGaZXRE',
    appId: '1:918558240173:ios:6686b50865a5fb9e78c524',
    messagingSenderId: '918558240173',
    projectId: 'music-videos-jjs',
    databaseURL: 'https://music-videos-jjs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-videos-jjs.appspot.com',
    iosClientId: '918558240173-0g8s5vlfbu5fhsh4br3335f2r6a95uo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicVideos',
  );
}
